apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource 
    resources:
      name: cpu 
      target: 
        type: Utilization
        averageUtilization: 50
      behavior: 
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent 
            value: 100
            periodSeconds: 15
        scaleUp:
          stabilizationWindowSeconds: 30
          policies:
          - type: Percent
            value: 100
            periodSeconds: 60
          - type: pods 
            value: 2
            periodSeconds: 20
          selectPolicy: Max   

                  